Japanese support
elvissteinjr/DesktopPlus pull request #69
Opened 2023-12-25 11:47 UTC by malken21

Added Japanese language support.

![image](https://github.com/elvissteinjr/DesktopPlus/assets/77374813/d263420c-04d0-46e1-9439-a1ec3745fda6)

2023-12-26 02:01 UTC, elvissteinjr requested changes
Thank you for your efforts!
While the NewUI branch is still going to get some additions with new translation strings, I don't see a reason to reject this. 
I'll also add some extra mention for community provided translations with authorship in the application itself when I have time.

If you're interested, the "input" folder also has translatable strings for the SteamVR controller binding screen (new files need to be added in "action_manifest.json" then as well).

I only really have the one nitpick with the name field. This seems good to me otherwise (as far as I am able to tell anyways).

2023-12-26 02:42 UTC, malken21 commented on assets/lang/ja.ini
> +Name=Japanize
I made a spelling mistake. Thank you for checking.

2023-12-27 02:18 UTC, elvissteinjr reviewed
I apologize for the second review here.
While I still can't check the Japanese itself as I don't speak it, I got curious and ran some machine translation back to English for a few sections. Of course this can't be fully trusted and has inaccuracies, but I still noticed two more things there.

I also noticed that I still had unpushed commits on my machine that added translation strings. Sorry about that.
This will still be unavoidable going forward and I'm not asking you to keep up with every change. Just wanted to let you know.

2023-12-28 02:37 UTC, malken21 commented on assets/lang/ja.ini
> +tstr_SettingsProfilesManage=プロファイル管理
I decided not to mention profiles.

2023-12-28 02:45 UTC, malken21 commented on assets/lang/ja.ini
> +tstr_SettingsTroubleshootingSettingsResetConfirmElementOverlays=Current オーバーレイセットアップ
I apologize. I neglected to translate that part.

2023-12-29 23:12 UTC, merged

2023-12-29 23:13 UTC, elvissteinjr commented
Looks good to me now. Thanks again for your efforts!

2024-02-07 02:36 UTC, elvissteinjr commented
Hi, I've recently pushed a few commits that added new translation strings. 
If you have the time, it would be great if these could be added to your Japanese translation as well.

I'm not looking to bother you like this every time new strings come up (this will inevitably keep happening), but I thought it would be good to at least have the translation be complete for the release it debuts in.
The next NewUI Preview build is planned to be released up soon. There are still some things I want to work on before this happens (so no need to rush), but nothing that would add more strings.

There's also a new "Author" field in the TranslationInfo section of translation files. This is displayed when the language is chosen and used to mark the translation as a community one. 
Feel free to put whatever name you're comfortable to be credited as in there.

I've also attached a version of the Japanese language file with the new strings already inserted in English, in case this helps (as .txt since GitHub doesn't allow .ini upload). 
If you prefer not to use it, keep in mind I've adjusted the naming scheme and removed some strings that weren't used anywhere, so it's not the exact same file from last time.
This would probably need to happen in a separate pull request I think? Not really sure to be honest.

Thanks!
[ja_new.txt](https://github.com/elvissteinjr/DesktopPlus/files/14188378/ja_new.txt)

2024-10-06 17:19 UTC, elvissteinjr commented
I'm fairly close to wrapping up for real this time, so I'll try to ask again.
I have attempted to contact you via the Twitter account on your profile, but I'm not sure how active you are on there and that site has failed to notify me of DMs before.

Suppose I'm looking somewhat desperate here for volunteer work, but I'd just find it cool to be able to announce full Japanese support for the 3.0 release.
Well, if you can't that's fine of course, don't get me wrong. Just want to at least have tried properly before looking for alternatives.

Thanks again.